
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class bookingform extends javax.swing.JFrame {

     public bookingform(String para,String u)
    {
        initComponents();
        jTextField6.setText(para);
        jTextField7.setText(u);
    }
    public bookingform() {
        initComponents();
                 

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        jButton3.setText("get");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BOOKING FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 210, 41));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TRAIN NOS", "TRAIN NAME", "DEPARTURE ", "ARRIVAL", "FARE", "FROM STATION", "TO STATION", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTable1ComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 840, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("TRAIN DETAILS:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 108, 21));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("BOOKING DETAILS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 122, 24));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("USER ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 65, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 141, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("EMAIL ID :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 21));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 141, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CHILDERN:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 74, 23));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 141, 23));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ADULTS:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 60, 22));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 141, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("TOTAL FARE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1484, 679, -1, 23));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("FARE AC1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 90, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("<---");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 0, -1, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 0, -1, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 835, -1, -1));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 900, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1572, 678, 83, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("PROCEED");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nagin.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marshall-mcluhans-106th-birthday-6207431578222592.3-law.gif"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 90));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("TOTAL FARE");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 80, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("0.0");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 70, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton5.setText("FARE AC 2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 90, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton6.setText("FARE AC 3");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 90, 20));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton7.setText("FARE SLEEPER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton8.setText("FARE GENERAL");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 140, 20));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 50, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("TOTAL SEAT:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
planmyjourney b=new planmyjourney();
b.setVisible(true);
dispose();
bookingform p=new bookingform();
p.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             int child,adult,s=0,newaac1,aac1= 0;
             child=Integer.parseInt(jTextField3.getText());
             adult=Integer.parseInt(jTextField4.getText());
            int f=child+adult;
             jTextField8.setText(f+"");
             int d1=Integer.parseInt(jTextField8.getText());
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railways","root","123123");
             PreparedStatement pstm=null;
             Statement st=con.createStatement();
              Statement sm=con.createStatement();
             ResultSet rs=st.executeQuery("select * from trains where from_station='"+jTextField6.getText()+"' AND to_station='"+jTextField7.getText()+"';");
             while(rs.next())
             {
                 aac1=Integer.parseInt(rs.getString("aac1"));
                 int fac1=Integer.parseInt(rs.getString("fac1"));
                 s=s+(child*fac1*adult);
             jLabel15.setText(String.valueOf(s));
           }
         newaac1=aac1-d1;
         String s3="Update trains Set  aac1='"+newaac1+"'  where from_station='"+jTextField6.getText()+"'";
            pstm=con.prepareStatement(s3);
            int i= pstm.executeUpdate(s3);
         if(i>0)
            {
         
            }
         Statement sn=con.createStatement();
         String query1="select * from trains where from_station='"+jTextField6.getText()+"';";
         ResultSet rt=sn.executeQuery(query1);
         while(rt.next()){
             String seat=rt.getString("aac1");
             jTextField5.setText(seat);
         }
         
         
         } catch (SQLException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       PreparedStatement pstm=null;
                 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railways","root","123123");
            Statement st=con.createStatement();
           
            ResultSet rs=st.executeQuery("select * from trains where from_station='"+jTextField6.getText()+"' AND to_station='"+jTextField7.getText()+"';");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
           
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(planmyjourney.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(planmyjourney.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentHidden

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String train_no,train_n,depar,arrival,fromst,tost;

         try {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railways","root","123123");
             Statement st=con.createStatement();
             
            ResultSet rs=st.executeQuery("select *from trains");
             while(rs.next())
             {
                 train_no=rs.getString("train_nos");
                train_n=rs.getString("train_name");
                depar=rs.getString("departure");
                arrival=rs.getString("arrival");
                fromst=rs.getString("from_station");
                tost=rs.getString("to_station");
                 userbooking.setTrain_no(train_no);
                 userbooking.setTrain_name(train_n);
                 userbooking.setDeparture(depar);
                 userbooking.setArrival(arrival);
                 userbooking.setFromstation(fromst);
                 userbooking.setTostation(tost);
             }
             
             userbooking.setUserid(jTextField1.getText());
             userbooking.setEmailid(jTextField2.getText());
             userbooking.setChild(jTextField3.getText());
             userbooking.setAdults(jTextField4.getText());
             userbooking.setFare(Integer.parseInt(jLabel15.getText()));
             
             int i=st.executeUpdate("insert into bookings values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+userbooking.getTrain_no()+"','"+userbooking.getTrain_name()+"','"+userbooking.getDeparture()+"','"+userbooking.getArrival()+"','"+userbooking.getFromstation()+"','"+userbooking.getTostation()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"');");
             if(i>0)
             {
                 completeyourpayment b=new completeyourpayment();
b.setVisible(true);
bookingform p=new bookingform();
p.setVisible(false);
dispose();
             }         } catch (SQLException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         }
         
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
             int child,adult,s=0,newaac2,aac2=0;
             child=Integer.parseInt(jTextField3.getText());
             adult=Integer.parseInt(jTextField4.getText());
             int f=child+adult;
             jTextField8.setText(f+"");
             int d1=Integer.parseInt(jTextField8.getText());
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railways","root","123123");
             PreparedStatement pstm=null;
             Statement st=con.createStatement();
             Statement sm=con.createStatement();
             ResultSet rs=st.executeQuery("select * from trains where from_station='"+jTextField6.getText()+"' AND to_station='"+jTextField7.getText()+"';");
             while(rs.next())
             {
                
                 aac2=Integer.parseInt(rs.getString("aac2"));
                 int fac2=Integer.parseInt(rs.getString("fac2"));
                 s=s+(child*fac2*adult);
             jLabel15.setText(String.valueOf(s));
             }
         newaac2=aac2-d1;
        String s3="Update trains Set  aac2='"+newaac2+"'  where from_station='"+jTextField6.getText()+"'";
            pstm=con.prepareStatement(s3);
            int i= pstm.executeUpdate(s3);
         if(i>0)
            {
         
            }
         Statement sn=con.createStatement();
         String query1="select * from trains where from_station='"+jTextField6.getText()+"';";
         ResultSet rt=sn.executeQuery(query1);
         while(rt.next()){
             String seat=rt.getString("aac2");
             jTextField5.setText(seat);
         }
        
        
        } catch (SQLException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try {
             int child,adult,s=0,newaac3,aac3=0;
             child=Integer.parseInt(jTextField3.getText());
             adult=Integer.parseInt(jTextField4.getText());
             int f=child+adult;
             jTextField8.setText(f+"");
             int d1=Integer.parseInt(jTextField8.getText());
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railways","root","123123");
              PreparedStatement pstm=null;
             Statement st=con.createStatement();
             Statement sm=con.createStatement();
             ResultSet rs=st.executeQuery("select * from trains where from_station='"+jTextField6.getText()+"' AND to_station='"+jTextField7.getText()+"';");
             while(rs.next())
             {
                aac3=Integer.parseInt(rs.getString("aac3"));
                 int fac3=Integer.parseInt(rs.getString("fac3"));
                 s=s+(child*fac3*adult);
             jLabel15.setText(String.valueOf(s));
             
             }
              newaac3=aac3-d1;
        String s3="Update trains Set  aac3='"+newaac3+"'  where from_station='"+jTextField6.getText()+"'";
            pstm=con.prepareStatement(s3);
            int i= pstm.executeUpdate(s3);
         if(i>=0)
            {
         
            }
         Statement sn=con.createStatement();
         String query1="select * from trains where from_station='"+jTextField6.getText()+"';";
         ResultSet rt=sn.executeQuery(query1);
         while(rt.next()){
             String seat=rt.getString("aac3");
             jTextField5.setText(seat);
         }
        
            
         } catch (SQLException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         try {
             int child,adult,s=0,newasl,asl=0;
             child=Integer.parseInt(jTextField3.getText());
             adult=Integer.parseInt(jTextField4.getText());
             int f=child+adult;
             jTextField8.setText(f+"");
             int d1=Integer.parseInt(jTextField8.getText());
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railways","root","123123");
             PreparedStatement pstm=null;
             Statement st=con.createStatement();
             Statement sm=con.createStatement();
             ResultSet rs=st.executeQuery("select * from trains where from_station='"+jTextField6.getText()+"' AND to_station='"+jTextField7.getText()+"';");
             while(rs.next())
             {
                 asl=Integer.parseInt(rs.getString("asl"));
                 int fsl=Integer.parseInt(rs.getString("fsl"));
                 s=s+(child*fsl*adult);
             jLabel15.setText(String.valueOf(s));
            
         }
         newasl=asl-d1;
        String s3="Update trains Set  asl='"+newasl+"'  where from_station='"+jTextField6.getText()+"'";
            pstm=con.prepareStatement(s3);
            int i= pstm.executeUpdate(s3);
         if(i>0)
            {
         
            }
         Statement sn=con.createStatement();
         String query1="select * from trains where from_station='"+jTextField6.getText()+"';";
         ResultSet rt=sn.executeQuery(query1);
         while(rt.next()){
             String seat=rt.getString("asl");
             jTextField5.setText(seat);
         }
         
         
         } catch (SQLException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       try {
             int child,adult,s=0;
             child=Integer.parseInt(jTextField3.getText());
             adult=Integer.parseInt(jTextField4.getText());
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railways","root","123123");
             Statement st=con.createStatement();
             
             ResultSet rs=st.executeQuery("select * from trains where from_station='"+jTextField6.getText()+"' AND to_station='"+jTextField7.getText()+"';");
             while(rs.next())
             {
                 int fg=Integer.parseInt(rs.getString("fg"));
                 s=s+(child*fg*adult);
             jLabel15.setText(String.valueOf(s));
            
         }} catch (SQLException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
          boolean status=validate.validateEmail(jTextField2.getText());
if(status){
    jLabel16.setText("EMAIL VALID");
}
else{
    jLabel16.setText("NOT VALID EMAIL");
}
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
         char ch=evt.getKeyChar();
       if(!(Character.isDigit(ch)))
       {
           evt.consume();
       }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
         char ch=evt.getKeyChar();
       if(!(Character.isDigit(ch)))
       {
           evt.consume();
       }
    }//GEN-LAST:event_jTextField4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
